import streamlit as st

st.title("Sii sempre serena")
st.subheader ("Megan Pellumbaj")
st.write("Serena,")
st.write("non è solo una bambina dopo un trucco di magia") 
st.write("è stare a casa ma in compagnia") 
st.write("o in silenzio sotto le coperte") 
st.write("e nelle avventure come le scoperte.") 
st.write("è l'emozione che non riconosci eppure rischi")
st.write("ad una festa con la musica") 
st.write("ma anche in solitudine sei unica") 
st.write("e se non la trovi,") 
st.write("basta che provi") 
st.write("a cercarla,")
st.write("tua, a farla")
st.write("e provarla:")
st.write("se veramente, la sera è sempre...")
st.write("sii sempre tu, Serena.")
st.feedback("stars")
